poses_scanner/segment_70: true
poses_scanner/segment_50: true
poses_scanner/segment_30: true
poses_scanner/zmin_70: -0.003
poses_scanner/zmin_50: -0.003
poses_scanner/zmin_30: -0.002
poses_scanner/seg_tol_70: 0.005
poses_scanner/seg_tol_50: 0.005
poses_scanner/seg_tol_30: 0.0045
poses_scanner/clustering_70: false
poses_scanner/clustering_50: false
poses_scanner/clustering_30: false
poses_scanner/rad_neigh_70: 25
poses_scanner/rad_neigh_50: 25
poses_scanner/rad_neigh_30: 35
