poses_scanner/zmin_70: -0.003
poses_scanner/zmin_50: -0.003
poses_scanner/zmin_30: -0.003
poses_scanner/segment_70: true
poses_scanner/segment_50: true
poses_scanner/segment_30: true
poses_scanner/seg_tol_70: 0.005
poses_scanner/seg_tol_50: 0.005
poses_scanner/seg_tol_30: 0.005
poses_scanner/outlier_removal_70: true
poses_scanner/outlier_removal_50: true
poses_scanner/outlier_removal_30: true
poses_scanner/radius_search_70: 0.01
poses_scanner/radius_search_50: 0.01
poses_scanner/radius_search_30: 0.01
poses_scanner/neighbors_70: 35
poses_scanner/neighbors_50: 35
poses_scanner/neighbors_30: 35
poses_scanner/clustering_70: false
poses_scanner/clustering_50: false
poses_scanner/clustering_30: false
poses_scanner/clus_tol_70: 0.008
poses_scanner/clus_tol_50: 0.008
poses_scanner/clus_tol_30: 0.008
poses_scanner/min_points_70: 200
poses_scanner/min_points_50: 200
poses_scanner/min_points_30: 200
poses_scanner/lwr_x: -0.65
poses_scanner/lwr_y: 0
poses_scanner/lwr_z: 0.13
poses_scanner/lwr_Roll: 1.57079
poses_scanner/lwr_Pitch: 0
poses_scanner/lwr_Yaw: 0
poses_scanner/lwr_rad: 0.8
