poses_scanner/segment_70: false
poses_scanner/segment_50: false
poses_scanner/segment_30: false
poses_scanner/zmin_70: 0.007
poses_scanner/zmin_50: 0.007
poses_scanner/zmin_30: 0.007
poses_scanner/seg_tol_70: 0.001
poses_scanner/seg_tol_50: 0.001
poses_scanner/seg_tol_30: 0.001
poses_scanner/neighbors_70: 25
poses_scanner/neighbors_50: 25
