poses_scanner/segment_70: false
poses_scanner/segment_50: false
poses_scanner/segment_30: false
poses_scanner/zmin_70: 0.007
poses_scanner/zmin_50: 0.007
poses_scanner/zmin_30: 0.007
poses_scanner/seg_tol_70: 0.001
poses_scanner/seg_tol_50: 0.001
poses_scanner/seg_tol_30: 0.001
poses_scanner/clustering_70: false
poses_scanner/clustering_50: false
poses_scanner/clustering_30: false
poses_scanner/rad_neigh_70: 25
poses_scanner/rad_neigh_50: 25
poses_scanner/rad_neigh_30: 35
poses_scanner/lwr_x: -0.65
poses_scanner/lwr_y: 0
poses_scanner/lwr_z: 0.13
poses_scanner/lwr_Roll: 1.57079
poses_scanner/lwr_Pitch: 0
poses_scanner/lwr_Yaw: 0
poses_scanner/lwr_rad: 0.8
